### ISSUE TITLE
Request for STAR RNA-seq aligner on ShARC

### ISSUE THREAD

**Issue by ljharrison1** [rcgsheffield/sheffield_hpc#1432]
Hello, I would please like to request the installation of the STAR RNA-seq software to ShARC ([github link](https://github.com/alexdobin/STAR)). This software is already installed on bessemer 

Many thanks,

Laura

**Comment by jkwmoore** [comment]
Hi Laura,

I can take a look at sorting this but as STAR does not appear to support using MPI (message passing) you are limited to SMP parallel environment jobs only. Running these jobs on ShARC will limit you to fewer cores (a maximum of 16) with a lower performance per core as ShARC is using older slower CPUs.

Can you explain why you would like the software on ShARC given the above?

Thanks,
James.

**Comment by ljharrison1** [comment]
Hi James,

I am only using ShARC as it gives me access to the shared filestore. I would prefer to use bessemer but it lacks options for long-term file storage 

Thanks,

Laura

**Comment by jkwmoore** [comment]
Hi Laura,

Shared file-store areas can be made available on Bessemer but they are subject to a few additional considerations which are detailed in our documentation:

https://docs.hpc.shef.ac.uk/en/latest/hpc/filestore.html#specifics-for-bessemer

I am going to add a ticket for you to our ticket tracking system to share some additional details and to get in contact with your shared area owner / PI in order to discuss this.

Thanks,
James.

**Comment by ljharrison1** [comment]
Hi James,

Thank you, that would be really useful.

Thanks,
Laura

**Comment by jkwmoore** [comment]
I can see that the storage team have now sorted this out for you so I will close the issue.

Cheers,
James.
