### ISSUE TITLE
Add JAGS to Bessemer

### ISSUE THREAD

**Issue by lucyannewinder** [rcgsheffield/sheffield_hpc#1446]
Hi,

Would it be possible to add JAGS software to Bessemer please?

Thanks

**Comment by jkwmoore** [comment]
If a sufficient number of users for this software wish to use it on the clusters we can look at getting this added.

Please file a ticket on via the University support desk (https://www.sheffield.ac.uk/nap/service/redirect/helpdesks) with this query answering the following questions :

- Which cluster/s do you wish for the software to be installed on?
- How many users are expected? (Please be specific and include usernames and/or research groups.)
- Does the software support the Linux operating system? (If the answer is no, then the software cannot be installed.)
- Please explain what the software does and how its use on HPC is justified?
- Does the software support parallel execution, if yes which methods? (SMP, MPI?)
- Does the software require licencing? (If yes, detail this as much as possible including details for setup or a licence server. Note we cannot install software which is not already licenced.)
- Please provide a link to the software documentation or otherwise provide it.
- Please provide a link to the software installation instructions or otherwise provide them.
- Please provide a link to the software download or otherwise provide the software.

Thanks,
James.

Note: I am closing this ticket, please do not re-open it or detail any sensitive info such as usernames publicly - please only do so via the support ticket.

**Comment by lucyannewinder** [comment]
Hello,

Can you provide more information about how/ where to file a ticket please?

Many thanks,
Lucy

**Comment by jkwmoore** [comment]
>Please file a ticket on via the University support desk (https://www.sheffield.ac.uk/nap/service/redirect/helpdesks) with this query answering the following questions :

Please click the link I provided, then click "Report a new issue" as shown below:

![image](https://user-images.githubusercontent.com/69149348/157280289-1b42a75c-4bb4-4f35-a3b2-4f6947472b72.png)
