### ISSUE TITLE
Request for salmon module

### ISSUE THREAD

**Issue by markdunning** [rcgsheffield/sheffield_hpc#1458]
Hi,

Could I please request a module for the salmon Bioinformatics tool?

It's a popular tool for sequencing analysis and I'm recommending it in several courses that I run

https://salmon.readthedocs.io/en/latest/building.html#installation

Thanks
Mark

**Comment by jkwmoore** [comment]
If a sufficient number of users for this software wish to use it on the clusters we can look at getting this added.

Please file a ticket on via the University support desk (https://www.sheffield.ac.uk/nap/service/redirect/helpdesks - click "Report a new issue") with this query answering the following questions :

- Which cluster/s do you wish for the software to be installed on?
- How many users are expected? (Please be specific and include usernames and/or research groups.)
- Does the software support the Linux operating system? (If the answer is no, then the software cannot be installed.)
- Please explain what the software does and how its use on HPC is justified?
- Does the software support parallel execution, if yes which methods? (SMP, MPI?)
- Does the software require licencing? (If yes, detail this as much as possible including details for setup or a licence server. Note we cannot install software which is not already licenced.)
- Please provide a link to the software documentation or otherwise provide it.
- Please provide a link to the software installation instructions or otherwise provide them.
- Please provide a link to the software download or otherwise provide the software.

If you ask that the ticket is forwarded to Research IT it will ensure it reaches us ASAP.

Thanks,
James.

Note: I am closing this issue on Github, please do not re-open it or detail any sensitive info such as usernames publicly - please only do so via the support ticket.
