### ISSUE TITLE
Installing sox 

### ISSUE THREAD

**Issue by asifjalal** [rcgsheffield/sheffield_hpc#1475]
How do I use 'sox' in bessemer? Getting this error "`sox is not installed."`

**Comment by jkwmoore** [comment]
Hi there,

We do not take installation requests via our documentation site Github and will normally request you get us some further details and submit the request via the central ticketing system (TopDesk.)

In this case since I am surprised SoX is missing and this is a quick painless install I have added it right away.

You should be able to load this module with:

`module load SoX/14.4.2-GCC-8.3.0`

----------------------------------------------------------

Please submit any further installation requests via the University support desk (https://www.sheffield.ac.uk/nap/service/redirect/helpdesks - click "Report a new issue") with this query answering the following questions :

- Which cluster/s do you wish for the software to be installed on?
- How many users are expected? (Please be specific and include usernames and/or research groups.)
- Does the software support the Linux operating system? (If the answer is no, then the software cannot be installed.)
- Please explain what the software does and how its use on HPC is justified?
- Does the software support parallel execution, if yes which methods? (SMP, MPI?)
- Does the software require licencing? (If yes, detail this as much as possible including details for setup or a licence server. Note we cannot install software which is not already licenced.)
- Please provide a link to the software documentation or otherwise provide it.
- Please provide a link to the software installation instructions or otherwise provide them.
- Please provide a link to the software download or otherwise provide the software.

If you ask that the ticket is forwarded to Research IT it will ensure it reaches us ASAP.

Thanks,
James.

**Comment by jkwmoore** [comment]
As this is now available on system and documented, I will now close this issue.
