### ISSUE TITLE
Documentation resource for site admins

### ISSUE THREAD

**Issue by Carldkennedy** [rcgsheffield/sheffield_hpc#1740]
A reference page for admins creating our hpc docs in a standardised way. Referenced from the README

Put in the reference info section*

 a note - for admins of the site

Ideas:
Code followed by how that renders and where we might want to use t
 ex. when to use warnings/notes etc page somewhere. 
internal links
External links
tabs etc etc

explain some of the global bits

Links to relevant sections in sphinx docs
 etc

**Comment by willfurnass** [comment]
Good idea.  The existing README is getting quite long.  Separate page in the docs or just a hidden `MAINTAINERS.md` in the repo?

**Comment by jkwmoore** [comment]
I was thinking that it could/should be a built page in the reference section with examples of the code used to build next to the rendered content.

Ideally I'd want to make it as discoverable for everyone publicly as much as possible rather than making it maintainers only - some of my customisations and why we have them may prove useful for other people working with Sphinx.
