### ISSUE TITLE
export LD_LIBRARY_PATH=... interferes with module loading (ShARC)

### ISSUE THREAD

**Issue by twinkarma** [rcgsheffield/sheffield_hpc#564]
I'm using this export command to link to my local conda's Python library path:

```
export LD_LIBRARY_PATH="/home/$USER/.conda/envs/caffe/lib:$LD_LIBRARY_PATH"
```

But it seems to interfere with any module commands that gets called afterwards e.g. `module avail`, `module load` and I get the following error:

```
init.c(556):ERROR:161: Cannot initialize TCL
```

What could be wrong? Are you not allowed to change any system variable that a module potentially uses?

**Comment by willfurnass** [comment]
The Module system uses Tcl, which is installed centrally (v8.5) and the necessary libraries are on the default search path so there is no need to consult `LD_LIBRARY_PATH` to find them.

Python always comes with v8.5 of the Tcl libraries; these will therefore be installed and available in the `lib` dir of every conda environment you create.  By adding this `lib` dir to `LD_LIBRARY_PATH` Python's Tcl library will used instead of the system Tcl library:

```bash
[$USER@sharc-node001 ~]$ ls -l /lib64/libtcl8.5.so 
-r-xr-xr-x. 1 root root 1242080 Nov 20  2015 /lib64/libtcl8.5.so

. activate caffe
export LD_LIBRARY_PATH="/home/$USER/.conda/envs/caffe/lib:$LD_LIBRARY_PATH

(caffe) [$USER@sharc-node001 ~]$ ldd $(which tclsh)
	libtcl8.5.so => /home/cs1wf/.conda/envs/caffe/lib/libtcl8.5.so (0x00002af32856d000)
```

My guess is that even though both libraries claim to be v8.5 that they're not interchangeable. 

Is it strictly necessary to manipulate `LD_LIBRARY_PATH` in this case?  Typically `. activate <envname>` is all that's required to use all software installed in a conda environment.

**Comment by karmauk** [comment]
No it's a Caffe dependency so if `libpython3.5m.0.1` (can't remember the exact name) is not found then it doesn't start.  I am thinking of rolling my own version of python with Caffe in the future seeing as we've found that Caffe does depend on the python library.

**Comment by drj11** [comment]
As an alternative you can set `LD_LIBRARY_PATH` where you start caffe.

    LD_LIBRARY_PATH="/home/$USER/.conda/envs/caffe/lib:$LD_LIBRARY_PATH" caffe

setting it like this means that `LD_LIBRARY_PATH` is only changed for the invocation of caffe, and not for any other commands.

**Comment by willfurnass** [comment]
@twinkarma still relevant?

**Comment by twinkarma** [comment]
Nope, the new module has its on version of Python and should not have the same problem.
