### ISSUE TITLE
Problem with R documentation for ShARC

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/sheffield_hpc#718]
The ShARC R page

http://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/R.html

Has a section for packages that require external libraries.  There seem to be some problems:

```
geos This is the library required for the rgeos package.
Geospatial Data Abstraction Library (GDAL) and PROJ.4 These are the libraries required for the rgdal package.
JAGS This is the library required for the rjags and runjags packages
```

All of the links point to **Iceberg** versions of the libraries. 

@annakrystalli -- It seems that you wrote this section of the docs for ShARC. Would you mind fixing the links please?

There currently isn't a JAGS install on ShARC (I know this because I'm about to do one) so perhaps just delete that one for now.

**Comment by annakrystalli** [comment]
Doh! yeah, can I do. Is it ok to do a quick patch just on github?

**Comment by annakrystalli** [comment]
Actually, I just edited around the original that was there so didn't actually put those links in. I'm unfamiliar with that type of linking (they look like internal references?) and not sure how I set it to the sharc links instead of iceberg links. @willfurnass any ideas? If you just point me in the right direction I'll get it done.
